# Generated by Django 3.2.13 on 2022-11-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='grade',
            field=models.FloatField(),
        ),
    ]
