# Generated by Django 3.2.13 on 2022-11-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='../static/images/profile/default.png', null=True, upload_to='profile/%Y%m%d/'),
        ),
    ]
